config/routes.rb
Rails.application.routes.draw do
  resources :member_lists
  root 'member_lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member_list.rb
class MemberList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/member_lists_controller.rb
class MemberListsController < ApplicationController
  before_action :set_member_list, only: [:show, :edit, :update, :destroy]

  # GET /member_lists
  # GET /member_lists.json
  def index
    @member_lists = MemberList.all
  end

  # GET /member_lists/1
  # GET /member_lists/1.json
  def show
  end

  # GET /member_lists/new
  def new
    @member_list = MemberList.new
  end

  # GET /member_lists/1/edit
  def edit
  end

  # POST /member_lists
  # POST /member_lists.json
  def create
    @member_list = MemberList.new(member_list_params)

    respond_to do |format|
      if @member_list.save
        format.html { redirect_to @member_list, notice: '報名成功！！' }
        format.json { render :show, status: :created, location: @member_list }
      else
        format.html { render :new }
        format.json { render json: @member_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_lists/1
  # PATCH/PUT /member_lists/1.json
  def update
    respond_to do |format|
      if @member_list.update(member_list_params)
        format.html { redirect_to @member_list, notice: '更新成功！！' }
        format.json { render :show, status: :ok, location: @member_list }
      else
        format.html { render :edit }
        format.json { render json: @member_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_lists/1
  # DELETE /member_lists/1.json
  def destroy
    @member_list.destroy
    respond_to do |format|
      format.html { redirect_to member_lists_url, notice: '刪除成功！！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_list
      @member_list = MemberList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_list_params
      params.require(:member_list).permit(:name_in_game, :name_in_discord, :player_id, :combat_capabilities, :player_job, :player_exability, :player_attribute, :needMVP, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_lists_helper.rb
module MemberListsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to '拉斐爾30連！！團報專區', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="">開團時間：2017/3/19 18：00</li>
        <br>
        <li>戰力五萬以上</li>
        <br>
        <li>因為屬性減傷,請用水屬</li>
      </ul>
    </div>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GBFGroupUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/member_lists/_form.html.erb
<%= form_for(member_list) do |f| %>
  <% if member_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member_list.errors.count, "error") %> prohibited this member_list from being saved:</h2>

      <ul>
      <% member_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    玩家名稱
    <% f.label :name_in_game %>
    <%= f.text_field :name_in_game %>
  </div>

  <div class="field">
    Discord名稱
    <% f.label :name_in_discord %>
    <%= f.text_field :name_in_discord %>
  </div>

  <div class="field">
    玩家ID
    <% f.label :player_id %>
    <%= f.text_field :player_id %>
  </div>

  <div class="field">
    戰力
    <% f.label :combat_capabilities %>
    <%= f.text_field :combat_capabilities %>
  </div>

  <div class="field">
    職業
    <% f.label :player_job %>
    <%= f.text_field :player_job %>
  </div>

  <div class="field">
    EX技能
    <% f.label :player_exability %>
    <%= f.text_field :player_exability %>
  </div>

  <div class="field">
    屬性
    <% f.label :player_attribute %>
    <%= f.text_field :player_attribute %>
  </div>

  <div class="field">
    MVP（要/不要）
    <% f.label :needMVP %>
    <%= f.text_field :needMVP %>
  </div>

  <div class="field">
    備註
    <% f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit ( f.object.new_record? ? "建立" : "更新"), class: "btn btn-info active"%>
  </div>
<% end %>

app/views/member_lists/edit.html.erb
<h1>Editing Member List</h1>

<%= render 'form', member_list: @member_list %>

<%= link_to 'Show', @member_list %> |
<%= link_to 'Back', member_lists_path %>

app/views/member_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>成員清單</h1>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>遊戲名稱</th>
      <th>Discord名稱</th>
      <th>玩家ID</th>
      <th>戰力</th>
      <th>職業</th>
      <th>EX技能</th>
      <th>玩家屬性</th>
      <th>MVP(要/不要)</th>
      <th>備註</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @i = 0 %>
    <% @member_lists.each do |member_list| %>
      <tr>
        <% if @i < 30 %>
        <% @i = @i + 1 %>
        
        <td><%= @i %></td>
        <% end %>
        <td><%= member_list.name_in_game %></td>
        <td><%= member_list.name_in_discord %></td>
        <td><%= member_list.player_id %></td>
        <td><%= member_list.combat_capabilities %></td>
        <td><%= member_list.player_job %></td>
        <td><%= member_list.player_exability %></td>
        <td><%= member_list.player_attribute %></td>
        <td><%= member_list.needMVP %></td>
        <td><%= member_list.notes %></td>
        <td><%= link_to '顯示', member_list, class: "btn btn-success active"%></td>
        <td><%= link_to '編輯', edit_member_list_path(member_list), class: "btn btn-warning active" %></td>
        <!--<td><%= link_to '刪除', member_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '報名', new_member_list_path, class: "btn btn-primary active"%>

app/views/member_lists/new.html.erb
<h1>資料填寫</h1>

<%= render 'form', member_list: @member_list %>

<%= link_to '返回', member_lists_path %>

app/views/member_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>遊戲名稱:</strong>
  <%= @member_list.name_in_game %>
</p>

<p>
  <strong>Discord名稱:</strong>
  <%= @member_list.name_in_discord %>
</p>

<p>
  <strong>玩家ID:</strong>
  <%= @member_list.player_id %>
</p>

<p>
  <strong>戰力:</strong>
  <%= @member_list.combat_capabilities %>
</p>

<p>
  <strong>職業:</strong>
  <%= @member_list.player_job %>
</p>

<p>
  <strong>EX技能:</strong>
  <%= @member_list.player_exability %>
</p>

<p>
  <strong>屬性:</strong>
  <%= @member_list.player_attribute %>
</p>

<p>
  <strong>MVP（要/不要）:</strong>
  <%= @member_list.needMVP %>
</p>

<p>
  <strong>備註:</strong>
  <%= @member_list.notes %>
</p>

<%= link_to '編輯', edit_member_list_path(@member_list) %> |
<%= link_to '返回', member_lists_path %>